spring.application.name=cbttest

spring.datasource.driver-class-name = org.h2.Driver
spring.datasource.url=jdbc:h2:~/db/cbtdb;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=utf-8
spring.thymeleaf.check-template-location=true
spring.thymeleaf.cache=false



